export enum FeedbackTypeEnum {
  SUPERVISOR_ANALYSIS = 'SUPERVISOR_ANALYSIS',
  STUDENT_RATING = 'STUDENT_RATING',
  PROFESSOR_FEEDBACK = 'PROFESSOR_FEEDBACK',
}

export enum RatingEnum {
  POOR = 1,
  FAIR = 2,
  GOOD = 3,
  VERY_GOOD = 4,
  EXCELLENT = 5,
}
