export enum ResourceTypeEnum {
  ARTICLE = 'ARTICLE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  LINK = 'LINK',
  BOOK = 'BOOK',
  PRACTICE_QUESTION = 'PRACTICE_QUESTION',
  QUIZ = 'QUIZ',
  OTHER = 'OTHER',
}

export enum ResourceCategoryEnum {
  STUDY_MATERIAL = 'STUDY_MATERIAL',
  PRACTICE_EXERCISE = 'PRACTICE_EXERCISE',
  REFERENCE = 'REFERENCE',
  TUTORIAL = 'TUTORIAL',
  ASSESSMENT = 'ASSESSMENT',
}
