export enum NotificationTypeEnum {
  MODULE_PUBLISHED = 'MODULE_PUBLISHED',
  MODULE_UNPUBLISHED = 'MODULE_UNPUBLISHED',
  QUIZ_ASSIGNED = 'QUIZ_ASSIGNED',
  QUIZ_ADDED_TO_COMPLETED_CHAPTER = 'QUIZ_ADDED_TO_COMPLETED_CHAPTER',
  CHAPTER_ADDED = 'CHAPTER_ADDED',
  PROFESSOR_ASSIGNED = 'PROFESSOR_ASSIGNED',
  PROFESSOR_UNASSIGNED = 'PROFESSOR_UNASSIGNED',
  GENERAL = 'GENERAL',
  // Forum-related notifications
  FORUM_NEW_DISCUSSION = 'FORUM_NEW_DISCUSSION',
  FORUM_NEW_REPLY = 'FORUM_NEW_REPLY',
  FORUM_NEW_SUB_REPLY = 'FORUM_NEW_SUB_REPLY',
  FORUM_LIKE = 'FORUM_LIKE',
  FORUM_REPORT = 'FORUM_REPORT',
  FORUM_DISCUSSION_ARCHIVED = 'FORUM_DISCUSSION_ARCHIVED',
  FORUM_MENTION = 'FORUM_MENTION',
  // Learning log review notifications
  LEARNING_LOG_REVIEWED = 'LEARNING_LOG_REVIEWED',
  // Anchor tag notifications
  ANCHOR_TAG_MISSED = 'ANCHOR_TAG_MISSED',
  // Enrollment notifications
  MODULE_ENROLLMENT = 'MODULE_ENROLLMENT',
  ACADEMIC_YEAR_ENROLLMENT = 'ACADEMIC_YEAR_ENROLLMENT',
  BULK_ENROLLMENT = 'BULK_ENROLLMENT',
  ENROLLMENT_WITHDRAWN = 'ENROLLMENT_WITHDRAWN',
}

export enum NotificationStatusEnum {
  UNREAD = 'UNREAD',
  READ = 'READ',
}

export const NOTIFICATION_CONSTANTS = {
  DEFAULT_METADATA: {},
  MAX_TITLE_LENGTH: 255,
  MAX_MESSAGE_LENGTH: 1000,
} as const;
