export enum NotificationTypeEnum {
  MODULE_PUBLISHED = 'MODULE_PUBLISHED',
  MODULE_UNPUBLISHED = 'MODULE_UNPUBLISHED',
  QUIZ_ASSIGNED = 'QUIZ_ASSIGNED',
  CHAPTER_ADDED = 'CHAPTER_ADDED',
  PROFESSOR_ASSIGNED = 'PROFESSOR_ASSIGNED',
  PROFESSOR_UNASSIGNED = 'PROFESSOR_UNASSIGNED',
  GENERAL = 'GENERAL',
  // Forum-related notifications
  FORUM_NEW_DISCUSSION = 'FORUM_NEW_DISCUSSION',
  FORUM_NEW_REPLY = 'FORUM_NEW_REPLY',
  FORUM_NEW_SUB_REPLY = 'FORUM_NEW_SUB_REPLY',
  FORUM_LIKE = 'FORUM_LIKE',
  FORUM_REPORT = 'FORUM_REPORT',
  FORUM_DISCUSSION_ARCHIVED = 'FORUM_DISCUSSION_ARCHIVED',
}

export enum NotificationStatusEnum {
  UNREAD = 'UNREAD',
  READ = 'READ',
}

export const NOTIFICATION_CONSTANTS = {
  DEFAULT_METADATA: {},
  MAX_TITLE_LENGTH: 255,
  MAX_MESSAGE_LENGTH: 1000,
} as const;
