export enum NotificationTypeEnum {
  MODULE_PUBLISHED = 'MODULE_PUBLISHED',
  MODULE_UNPUBLISHED = 'MODULE_UNPUBLISHED',
  QUIZ_ASSIGNED = 'QUIZ_ASSIGNED',
  CHAPTER_ADDED = 'CHAPTER_ADDED',
  PROFESSOR_ASSIGNED = 'PROFESSOR_ASSIGNED',
  PROFESSOR_UNASSIGNED = 'PROFESSOR_UNASSIGNED',
  GENERAL = 'GENERAL',
}

export enum NotificationStatusEnum {
  UNREAD = 'UNREAD',
  READ = 'READ',
}

export const NOTIFICATION_CONSTANTS = {
  DEFAULT_METADATA: {},
  MAX_TITLE_LENGTH: 255,
  MAX_MESSAGE_LENGTH: 1000,
} as const;
