export enum QuizCategoryEnum {
  ASSESSMENT = 'ASSESSMENT',
  COMMUNICATION = 'COMMUNICATION',
  ANXIETY = 'ANXIETY',
  TRAUMA = 'TRAUMA',
}

export enum QuizTypeEnum {
  MODULE = 'MODULE',
  CHAPTER = 'CHAPTER',
}

export enum QuizQuestionTypeEnum {
  MULTI_SELECT = 'MULTI_SELECT',
  SINGLE_SELECT = 'SINGLE_SELECT',
  SCENARIO_BASED = 'SCENARIO_BASED',
} 