export enum QuizTypeEnum {
  MODULE = 'MODULE',
  CHAPTER = 'CHAPTER',
  ANCHOR_TAG = 'ANCHOR_TAG',
}

export enum QuizQuestionTypeEnum {
  MULTI_SELECT = 'MULTI_SELECT',
  SINGLE_SELECT = 'SINGLE_SELECT',
  SCENARIO_BASED = 'SCENARIO_BASED',
}
